# Generated by Django 3.2.9 on 2022-06-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0015_alter_userrequest_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ProfilePicture',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='ProofPic2',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='Title',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
